### ISSUE TITLE
Unused variable warnings while optimised build

### ISSUE THREAD

**Issue by jig08** [hashkat/hashkat#125]
Warnings thrown while optimized build of `hashkat`.

Maybe we should do away with these...

- [x] **src/analyzer_follow.cpp**
```
hashkat/src/analyzer_follow.cpp
330:23: warning: unused variable ‘try_agent’ [-Wunused-variable]
Agent& try_agent = network[agent_to_follow];
```

- [x] **src/analyzer_main.cpp**
```
hashkat/src/analyzer_main.cpp
440:10: warning: unused variable ‘e_author’ [-Wunused-variable]
   Agent& e_author = network[choice.id_author];
```

- [x] **src/analyzer_follow.cpp**
```
hashkat/src/analyzer_follow.cpp
454:16: warning: unused variable ‘rand_num’ [-Wunused-variable]
double rand_num = rng.rand_real_not0();
```

- [x] **src/io.cpp**
```
hashkat/src/io.cpp
81:16: warning: unused variable ‘tb’ [-Wunused-variable]
TweetBank& tb = state.tweet_bank;
```

- [x] **src/io.cpp**
```
hashkat/src/io.cpp
108:9: warning: unused variable ‘MAX_AGENTS’ [-Wunused-variable]
int MAX_AGENTS = C.max_agents;
```
- [x] **src/unit_tests/02_Tweeting.cpp**
```
hashkat/src/unit_tests/02_Tweeting.cpp
56:21: warning: unused variable ‘r’ [-Wunused-variable]
int r = vec_tree.pick_random_weighted(rng);
    ^
```
- [x] **src/TweetBank.cpp**

```
hashkat/src/TweetBank.cpp
50:14: warning: unused variable ‘lang’ [-Wunused-variable]
Language lang = agent.language;
```

- [x] **src/io.cpp**
```
hashkat/src/io.cpp
109:12: warning: unused variable ‘rate_add’ [-Wunused-variable]
double rate_add = C.rate_add;
```

- [x] **src/analyzer_rates.cpp**
```
hashkat/src/analyzer_rates.cpp
114:17: warning: unused variable ‘overall_retweet_rate’ [-Wunused-variable]
overall_retweet_rate = 0;
```

- [x] **src/io.cpp**
```
hashkat/src/io.cpp
873:20: warning: unused variable ‘e’ [-Wunused-variable]
Agent& e = network[id_fol];
```

- [x] **src/io.cpp**
```
hashkat/src/io.cpp
488:41: warning: unused variable ‘scale’ [-Wunused-variable]
char out[100], in[100], cumul[100], scale[100];
```

- [ ] **src/io.cpp**
```
hashkat/src/io.cpp
444:12: warning: unused variable ‘average_degree’ [-Wunused-variable]
     double average_degree = (double)sum_k / (double)network.size();
```

- [x] **src/analyzer_main.cpp**
```
hashkat/src/analyzer_main.cpp
442:20: warning: unused variable ‘obs_pref_class’ [-Wunused-variable]
   PreferenceClass& obs_pref_class = config.pref_classes[e_observer.preference_class];
```

- [ ] **src/RateTree.h**
```
hashkat/src/RateTree.h
284:13: warning: unused variable ‘occurrences’ [-Wunused-variable]
int occurrences = 0;
```

- [x] **src/TweetBank.cpp**
```
hashkat/src/TweetBank.cpp
51:18: warning: unused variable ‘followers’ [-Wunused-variable]
     FollowerSet& followers = agent.follower_set;
```

- [ ] **src/unit_tests/02_Tweeting.cpp**
```
hashkat/src/unit_tests/02_Tweeting.cpp
56:21: warning: unused variable ‘r’ [-Wunused-variable]
                 int r = vec_tree.pick_random_weighted(rng);
```

**Comment by jig08** [comment]
**TODO:** Instead of commenting, remove the "unused variables" altogether.

**Comment by jig08** [comment]
All removed, closing this issue.
